### ISSUE TITLE
Possibility to override defaultOptions on alert()/info()/success()/etc.

### ISSUE THREAD

**Issue by skle** [erobertson42/bootstrap-modbox#13]
It would be nice to be able to override the defaultOptions for each of the default modal types.

For example:

`modbox.defaultOptions.title = ''`

This sets the default title to nothing.

But when using:

`modbox.alert('test')`

The title is set to 'Alert'. Is it possible to add an option like this?

`modbox.defaultOptions.alert.title = ''`

or

`modbox.defaultOptions.confirm.title = ''`

Ps. I'm aware of this option:

`modbox.alert({title:'', body:'test'})`

**Comment by erobertson42** [comment]
Thanks, that's not a bad idea to have defaults for the different modal types.  However, because of how the way the `defaultOptions` object is used all over the place in the code, I'm not sure if I want to pollute it with multiple copies of itself for each type of modal.

Also, if added, I don't think it would be just `alert`, `confirm`, and `prompt`.  There should probably be a way to set options for each alert variant as well: `success`, `info`, `danger`, and `warning`.

I'll have to put some thought into the best way to implement it.  Any suggestions welcome.

**Comment by skle** [comment]
Maybe use a function like Bootbox uses:

`bootbox.setDefaults(object options)`

And extend it to something like this:

`modbox.setDefaults(string type, object options)`

For Example:

```
modbox.setDefaults('alert', {title:''});
modbox.setDefaults('confirm', {title:''});
modbox.setDefaults('prompt', {title:''});
modbox.setDefaults('success', {title:''});
modbox.setDefaults('info', {title:''});
modbox.setDefaults('danger', {title:''});
modbox.setDefaults('warning', {title:''});
```

This way, the defaultOptions object can be inherited by each type and individual options can be easily set for each type.

**Comment by erobertson42** [comment]
Thank you for the suggestion, and yeah, I was thinking something very similar.  I plan to add this as soon as I get an opportunity.

**Comment by erobertson42** [comment]
New [v1.6.0](https://github.com/erobertson42/bootstrap-modbox/releases/tag/v1.6.0) release adds this.  Everything seems good in my testing, but there's a lot of interaction between all the various ways of setting options, so I hope I didn't break something.

Please let me know if this works out.

**Comment by skle** [comment]
Just tested this and works great.
Thanks a lot for your time and work. Much appreciated!
