### ISSUE TITLE
Show / Hide for alert, prompt, and confirm

### ISSUE THREAD

**Issue by ray73864** [erobertson42/bootstrap-modbox#20]
I realise I could use the custom modal for this, but it would be nice if I could set these 3 modal types to not auto-open.

In my particular use-case, when I am running an XMLHttpRequest / Fetch, if I know it is going to take a few seconds, I like to show an alert when the request starts, and then hide it when the request finishes.

In the past with something like Bootbox, I have used an 'alert' set to not auto-show, then in my onLoadStart function, I 'show()' the modal, and in the onLoadEnd function, I 'hide()' the modal.

If I could do something like

```
let myModal = modal.alert({ message: "Test", show: false });

xhr = XMLHttpRequest();
xhr.onloadstart = (e) => { myModal.show(); };
xhr.onloadend = (e) => { myModal.hide(); };
```

That would be perfect.

Right now I am doing

```
let myModal = new modbox({
  title: "Alert",
  message: "Test",
  destroyOnClose: true
});

xhr = XMLHttpRequest();
xhr.onloadstart = (e) => { myModal.show(); };
xhr.onloadend = (e) => { myModal.hide(); };
```

And while it works, it's basically just duplicating what modal.alert already does with the exception of being able to show/hide on command.

**Comment by erobertson42** [comment]
Unfortunately, it wouldn't be possible for it to work quite like that.  Those modal types use a promise-based approach by design.  For your particular use-case, starting with a custom modal (`new modbox()`) is exactly how it's meant to be used.

Technically, I could add some new option to prevent those modal types from returning a promise, but that's kind of the opposite of their purpose, and would just be duplicating functionality that already exists.

I do appreciate the suggestion, but this is behaving as designed.
