### ISSUE TITLE
Option To Hide Header Close Button

### ISSUE THREAD

**Issue by abarreras-intercarve** [erobertson42/bootstrap-modbox#8]
There needs to be an option for hiding the X close button on the header when desired.

**Comment by aldobarr** [comment]
@erobertson42 I opened a [pull request](https://github.com/erobertson42/bootstrap-modbox/pull/9) for this enhancement. Hope this helps!

**Comment by erobertson42** [comment]
Thanks for taking the time to submit a pull request.  Normally I'd be happy to accept it, but I think I'd like to implement this a little differently, which is also going to require I update some other code to match the desired method.

Basically, instead of excluding the button markup entirely, I want to always add the close button to the DOM, but just hide it if the new option dictates.  That way it's available if you want to dynamically show it later.  Unfortunately, the markup for the entire header also works that way (not rendered to DOM), so I'd like to update that as well.

I should have an update soon.

**Comment by erobertson42** [comment]
This is now included with the v1.4.0 release.
